const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'huberman-kb-additions.csv');

function csvEscape(v) {
  const s = String(v == null ? '' : v).replace(/\r?\n/g, ' ').trim();
  if (/[",]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
  return s;
}

const topic = 'exposicion-a-la-luz-y-ritmo-circadiano';

const takeaways = [
  "El reloj circadiano humano funciona en ciclos de ~24.2 horas - la luz lo ajusta a exactamente 24. Sin exposicion diaria a la luz te desfasas ~12 minutos por dia; despues de 25 dias estas 5-6 horas fuera de fase - con jet lag en tu propia casa. La luz solar matutina reinicia el reloj a exactamente 24 horas cada dia.",
  "Las ipRGCs (celulas con melanopsina) son los fotorreceptores dedicados a fijar el reloj en el ojo. Codescubiertas por Hattar, David Berson e Ignacio Provencio, este ~1-2% de las celulas ganglionares de la retina son intrinsecamente fotosensibles, proyectan al NSQ (reloj maestro) y a otras regiones cerebrales no visuales, y operan de forma completamente independiente de la vision por bastones/conos. Personas ciegas a nivel de imagen pero con ojos intactos suelen mantener un arrastre circadiano normal.",
  "Consigue 10-15 minutos de luz al aire libre dentro de la primera hora despues de despertar. Incluso en dias nublados, la luz exterior supera ampliamente la intensidad de la luz artificial interior. La sombra en un dia soleado es suficiente; no se requiere mirar directamente al sol. En dias muy oscuros, extiende a 30-45 minutos o usa una caja de terapia de luz.",
  "La luz brillante entre las 10 pm y las 4 am suprime directamente el animo y perjudica el aprendizaje, independientemente de la disrupcion circadiana o la privacion de sueno. Esto esta mediado por el nucleo perihabenular (el 'nucleo Hattar-Fernandez'), una region cerebral que recibe input directo de las ipRGCs y modula el afecto y la cognicion via la corteza prefrontal ventromedial.",
  "El Modelo Tripartito: tres sistemas deben alinearse para la salud. (1) Reloj circadiano guiado por la luz; (2) impulso homeostatico del sueno (adenosina); (3) inputs ambientales directos (luz, estres). Optimizar solo uno es insuficiente - los tres deben converger. El mismo marco aplica a la alimentacion: el impulso de hambre del nucleo arcuato + la compuerta luz-oscuridad del NSQ + un tercer circuito de escasez de comida.",
  "El horario de la luz controla el apetito y el metabolismo, no solo el sueno. El NSQ regula las senales de hambre del nucleo arcuato; un tercer circuito independiente de ambos impulsa la busqueda de comida cuando esta escasea. Alinear los horarios de comida con la exposicion a luz afecta significativamente el peso corporal. Hattar perdio ~25 kg al adelantar sus horarios de comida para calzar con su fase circadiana.",
  "La luz brillante del mediodia mejora el animo independientemente del ajuste del reloj. La luz brillante exterior al mediodia activa el nucleo perihabenular, mejorando el animo y el estado de alerta por un mecanismo separado del arrastre circadiano. Hattar llama a esto satisfacer el 'hambre de luz'.",
  "El horario de verano es biologicamente danino. El adelanto de primavera empuja la exposicion a luz mas tarde cuando los largos dias de verano ya retrasan el reloj, alterando la progresion estacional suave de las senales luminicas y aumentando riesgos de salud. Estudios muestran que las regiones que mantienen horario de verano todo el ano tienen tasas mas altas de cancer y depresion que las que usan horario estandar.",
  "La recuperacion del jet lag requiere coordinar la luz, las comidas, y el minimo de temperatura simultaneamente. La luz justo despues del minimo de temperatura adelanta el reloj (viajar al este); la luz justo antes lo retrasa (viajar al oeste). Comer en el horario local inmediatamente al llegar acelera aun mas la adaptacion. De forma critica, ver la luz equivocada al llegar (ej. un hermoso amanecer italiano recien bajado de un vuelo desde Nueva York) desplazara tu reloj mas en la direccion equivocada.",
  "El color de ojos afecta la sensibilidad individual a la luz. Las personas de ojos claros son mas sensibles a la luz y pueden necesitar menos exposicion a luz matutina, pero son mas vulnerables a la disrupcion por luz nocturna. Las personas de ojos oscuros pueden necesitar sesiones matutinas de luz mas largas. Los pacientes con trastorno bipolar tambien parecen tener sensibilidades distintas a la luz.",
  "Los cambios estacionales en la duracion del dia alteran el animo, la energia y la cognicion - incluso sin depresion estacional clinica. Las personas en regiones de alta latitud muestran patrones estacionales claros en energia, motivacion y apetito que siguen el fotoperiodo. La luz artificial altera el ritmo estacional en animales y humanos. Mantener una alineacion consistente de luz-comida-ejercicio durante todo el ano amortigua estos efectos.",
  "Despertar en medio de la noche puede indicar desalineacion circadiana, no insomnio. Si tu manana biologica comienza a las 4 am pero te dormiste a medianoche, el despertar nocturno es tu cuerpo tratando el sueno de la primera parte de la noche como una siesta. La solucion es ajustar el horario de sueno, no tratar el despertar. Usar luz brillante del bano al despertar de noche puede empeorar el problema."
];

const protocols = [
  "Exposicion a luz matutina. Que: Exposicion a luz exterior poco despues de despertar para ajustar el reloj circadiano. Como: Sal afuera (no a traves de vidrio) por 10-15 min en dias soleados o parcialmente nublados; 30-45 min en dias muy nublados. Sin lentes de sol. La sombra en un dia brillante es suficiente - no necesitas mirar directamente al sol. En dias muy oscuros de invierno nordico, usa una lampara de terapia de luz de 10.000 lux a la altura de la cara. Si te saltas un dia, compensa con mas duracion al dia siguiente. Cuando: Dentro de la primera hora despues de despertar, idealmente dentro de los primeros 30 minutos.",
  "Luz de mediodia para el animo. Que: Exposicion adicional a luz brillante exterior al mediodia para estimular el nucleo perihabenular y elevar el animo independientemente del ajuste del reloj. Como: 10-20 minutos afuera alrededor del mediodia. Manten las ventanas de la oficina abiertas si es posible - esto es 'hambre de luz', el sistema quiere luz al mediodia separado de su dosis matutina de sincronizacion. Cuando: Aproximadamente entre las 10 am y las 3 pm.",
  "Manejo de luz nocturna y de la tarde-noche. Que: Reducir toda la luz artificial despues del atardecer; mantener casi oscuridad total entre las 10 pm y las 4 am. Como: Atenua progresivamente las luces interiores despues del atardecer. Usa luz roja tenue (menos de 10 lux) si se necesita algo de luz de noche. Atenua las pantallas al minimo brillo. Hattar prefiere atenuar todas las luces en vez de usar lentes bloqueadores de luz azul, que considera proteccion incompleta. Guardar el telefono en una bolsa nocturna elimina la luz y la distraccion a la vez. Cuando: Comenzando al atardecer; estricto entre las 10 pm y las 4 am.",
  "Prueba de luz minima para determinar el cronotipo. Que: Determinar tu verdadera preferencia biologica de sueno-vigilia eliminando la luz artificial y las senales de horario. Como: Durante 3-7 dias (acampando o en un ambiente controlado de poca luz), evita alarmas y luz artificial. Duerme cuando tengas sueno real; despierta espontaneamente. El patron natural que emerge despues de 2-3 dias refleja tu verdadero cronotipo. Cuando: Evaluacion unica de referencia; aplica los resultados al diseno de tu horario.",
  "Horario de comidas alineado a la fase circadiana. Que: Comer la mayoria de las calorias en la primera mitad de tu dia de vigilia, sincronizado con tu hora de despertar anclada a la luz. Como: Ancla la primera comida cerca de tu hora de despertar. Reduce la ingesta hacia la segunda mitad del dia. Evita comer cuando tu sistema circadiano espera dormir. Horarios de comida regulares a horas consistentes refuerzan la senal circadiana. Cuando: Horario diario consistente - la regularidad importa tanto como el horario en si.",
  "Horario de ejercicio para vigor maximo. Que: Programar el ejercicio para que coincida con tu periodo de maximo estado de alerta, que sigue tu fase circadiana. Como: Identifica tu ventana subjetiva de maximo estado de alerta (tipicamente 4-6 horas despues de despertar). Programa los entrenamientos ahi. Alinear ejercicio, luz y comidas dentro de la misma ventana de fase circadiana amplifica el rendimiento y mejora la calidad del sueno posterior. Cuando: Diario; dentro de la ventana de vigor maximo identificada.",
  "Protocolo de jet lag y cambio de reloj. Que: Reajuste circadiano rapido usando el horario de luz, las comidas, y el minimo de temperatura. Como: 1) Encuentra tu minimo de temperatura (aprox. 90 min antes de tu hora habitual de despertar). 2) Para adelantar el reloj (viajar al este): luz brillante justo despues del minimo de temperatura. 3) Para retrasar el reloj (viajar al oeste): luz brillante justo antes del minimo de temperatura. 4) Evita la luz en el momento equivocado al llegar. 5) Come en el horario local inmediatamente al llegar. 6) Para viajes largos, comienza a ajustar 2-3 dias antes de partir. Cuando: Comienza antes de viajar; aplica continuamente en el destino.",
  "Recuperacion tras una noche trasnochada aislada. Que: Volver a tu horario normal despues de una noche tardia aislada sin componer la disrupcion. Como: Permite dormir proporcionalmente mas la manana siguiente (ej. dormirte 3 horas mas tarde -> despertar ~2 horas mas tarde). No fuerces tu hora normal de despertar viendo luz brillante de inmediato. La noche siguiente, vuelve a tu hora normal de dormir. Un sistema bien anclado se recupera de una sola noche tardia en 1-2 dias. Cuando: Segun se necesite, tras trasnochadas sociales o disrupciones inesperadas.",
  "Optimizacion tripartita (alineacion completa del sistema). Que: Alinear los tres componentes del Modelo Tripartito simultaneamente para maximo animo, cognicion y salud metabolica. Como: 1) Circadiano: luz matutina exterior dentro de los primeros 30 min de despertar; evitar luz brillante despues de las 10 pm. 2) Impulso de sueno: hora fija de despertar los 7 dias de la semana; siestas menores a 20 min y antes de las 3 pm. 3) Luz/ambiente directo: luz brillante al mediodia; manejar estres e intensidad de luz juntos. Integra horario de comidas y ejercicio en la misma ventana circadiana. Cuando: Practica diaria continua - la consistencia a largo plazo es lo que da el beneficio."
];

const overview = "Episodio 43 - Timing Light, Food & Exercise for Better Sleep, Energy & Mood (invitado: Dr. Samer Hattar). El Dr. Samer Hattar, codescubridor de las celulas ganglionares de la retina intrinsecamente fotosensibles (ipRGCs) que fijan el reloj circadiano humano, explica como la luz, los horarios de alimentacion y el momento del ejercicio interactuan para determinar el estado de animo, el aprendizaje, el apetito y el rendimiento fisico. Presenta el 'Modelo Tripartito' de salud: el sistema circadiano, el impulso homeostatico del sueno, y los inputs ambientales directos deben alinearse para un bienestar optimo. Incluye protocolos para exposicion a luz matutina, recuperacion de jet lag, ajuste de cronotipo, y por que evitar la luz brillante entre las 10 pm y las 4 am.";

const recursos = "Recursos y estudios mencionados en el episodio 43 (Timing Light, Food & Exercise for Better Sleep, Energy & Mood): libro 'El Codigo Circadiano' de Satchin Panda sobre alimentacion con restriccion horaria y salud circadiana. Estudios de biomarcadores de fase circadiana por RNA de Phyllis Zee y Achim Kramer (miden transcritos de RNA para determinar la fase circadiana desde una sola muestra de sangre). Experimentos de campamento de Ken Wright sobre cronotipo y luz artificial. Investigacion de Jamie Zeitzer sobre destellos de luz en la madrugada y su efecto en el sueno total.";

const rows = [];
takeaways.forEach((t, i) => rows.push([`hub-ep043-tk${i + 1}`, topic, t, 'true']));
protocols.forEach((p, i) => rows.push([`hub-ep043-proto${i + 1}`, topic, p, 'true']));
rows.push(['hub-ep043-overview', topic, overview, 'true']);
rows.push(['hub-ep043-recursos', topic, recursos, 'true']);

const lines = rows.map(r => r.map(csvEscape).join(','));
fs.appendFileSync(OUT, '\n' + lines.join('\n'), 'utf8');
console.log(JSON.stringify({ rowsAppended: rows.length }, null, 2));
